### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by hertzmann** [chuanli11/MGANs#2]
The results I'm getting on the VG style aren't very good. I'd tried reproducing Figure 12, upper left, using this input image: [Tubingen](https://raw.githubusercontent.com/jcjohnson/neural-style/master/examples/inputs/tubingen.jpg)

With max_length=1024, the result looks like 
![tubingen_mgans](https://cloud.githubusercontent.com/assets/5560050/14691323/70e31a16-0705-11e6-826b-bb265f4b2ce7.jpg)

Adjusting the image size and noise level parameters didn't improve things.

**Comment by chuanli11** [comment]
Figure 12, upper left used a network trained with a different painting (starry night) from VG. The network you are using now is trained with this image

![vg_apilles](https://cloud.githubusercontent.com/assets/15967400/14691710/0bbb692e-0753-11e6-915f-e7d9dff18ed4.jpg)

Having said that, i admit the result is not so great, in particular the sky. The method has difficulties in dealing with regions that do not excite the VGG network. This usually happens to the homogenous background as discussed in the paper.

**Comment by austingg** [comment]
I have done some experiments  on portrait images. There is often a contour surrounding the portrait when the background is homogeneous.

**Comment by hertzmann** [comment]
Got it. Thanks!
