### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by CJHFUTURE** [chuanli11/MGANs#3]
Hi, When do you think you will release the training code?

**Comment by chuanli11** [comment]
Hi, Thanks for your interests. We should be able to release the training code in about two weeks.

**Comment by CJHFUTURE** [comment]
Wow, awesome!Also can this be run in cpu mode?

Sent from Outlook Mobile

On Wed, May 4, 2016 at 11:08 PM -0700, "chuanli11" notifications@github.com wrote:

Hi, Thanks for your interests. We should be able to release the training code in about two weeks.

---

**Comment by CJHFUTURE** [comment]
How long does the training take and on what gpu out of interest?

Sent from Outlook Mobile

On Wed, May 4, 2016 at 11:08 PM -0700, "chuanli11" notifications@github.com wrote:

Hi, Thanks for your interests. We should be able to release the training code in about two weeks.

---

**Comment by chuanli11** [comment]
Hi, 

Here are some preliminary figures: a Titan X takes about an hour to train a model. Generating training data takes another hour or so. Other cards such as GTX980 should also do the job. 

The first release will not support cpu.

**Comment by rcorin** [comment]
Hello! cool work!  
"The first release will not support cpu."
But will the generated models (trained with GPU) be able to be used in CPU, or we need also GPU for sampling?
thx

**Comment by DanielDanielDanielDanielDaniel** [comment]
Can I marry you?

**Comment by chuanli11** [comment]
Training code released now. Welcome to feedback!
